# Generated by Django 5.2.8 on 2025-11-29 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='inicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
