# Generated by Django 5.2.8 on 2025-11-29 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_alergias_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescricao',
            old_name='data_hora',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('encerrada', 'Encerrada')], default='ativa', max_length=20),
        ),
    ]
