# Generated by Django 5.2.8 on 2025-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alerta_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('prescricao', 'Relacionado à prescrição'), ('outro', 'Outro alerta clínico')], default='outro', max_length=20),
        ),
    ]
