# Generated by Django 5.2.8 on 2025-12-01 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alerta_tipo_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='hora_diaria',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='hora_semanal',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='horarios_multiplos',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='recorrencia',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alerta',
            name='repetir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='repetir_intervalo',
            field=models.CharField(blank=True, choices=[('4h', 'A cada 4 horas'), ('6h', 'A cada 6 horas'), ('8h', 'A cada 8 horas'), ('12h', 'A cada 12 horas'), ('24h', 'A cada 24 horas'), ('semanal', 'Uma vez por semana')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('prescricao', 'Relacionado à prescrição'), ('outro', 'Outro alerta clínico')], default='prescricao', max_length=20),
        ),
    ]
